version: '3'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=<username>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=italian_restaurant
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=<url>
      - SPRING_DATASOURCE_USERNAME=<username>
      - SPRING_DATASOURCE_PASSWORD=<password>
      - SPRING_MAIL_HOST=<host>
      - SPRING_MAIL_PORT=<port>
      - SPRING_MAIL_USERNAME=<email>
      - SPRING_MAIL_PASSWORD=<password>
      - JWT_SECRET_KEY=<secret-key>
      - JWT_EXPIRATION=<expiration>

  frontend:
    container_name: frontend
    build:
      context: ./frontend/ItalianRestaurantFront/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    expose:
      - "80"

volumes:
  db:
    driver: local