version: '3'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=italian_restaurant
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./ItalianRestaurantBackend/
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    restart: no
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/italian_restaurant
      - SPRING_DATASOURCE_USERNAME=<username>
      - SPRING_DATASOURCE_PASSWORD=<password>
      - SPRING_MAIL_HOST=<host>
      - SPRING_MAIL_PORT=<port>
      - SPRING_MAIL_USERNAME=<username>
      - SPRING_MAIL_PASSWORD=<password>
      - JWT_SECRET_KEY=<secret>
      - JWT_EXPIRATION=168
      - GOOGLE_CLIENT_ID=<id>
      - GOOGLE_CLIENT_SECRET=<secret>
      - FACEBOOK_CLIENT_ID=<id>
      - FACEBOOK_CLIENT_SECRET=<secret>
      - GITHUB_CLIENT_ID=<id>
      - GITHUB_CLIENT_SECRET=<secret>
      - SERVER_IP=<ip>
      - AWS_ACCESS_KEY=<key>
      - AWS_SECRET_KEY=<key>
      - AWS_BUCKET_NAME=<name>
      - STRIPE_SECRET_KEY=<key>
      - STRIPE_WEBHOOK_SECRET=<secret>
  frontend:
    container_name: frontend
    build:
      context: ./ItalianRestaurantFrontend/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: no

volumes:
  db:
    driver: local