spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/italian_restaurant
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

add-sample-users-data: false

application:
  security:
    jwt:
      secret-key: 50645367556B58703273357638792F423F4528482B4D6251655468576D597133
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

