spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/italian_restaurant
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: <email>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 50645367556B58703273357638792F423F4528482B4D6251655468576D597133
      expiration: 300000

server-url: http://localhost:4200

server:
  error:
    include-message: always