spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
app:
  security:
    jwt:
      tokenSecret: ${JWT_SECRET_KEY}
    cors:
      allowedOrigins: https://${SERVER_IP}
    oauth2:
      authorizedRedirectUris:
        - https://${SERVER_IP}/oauth2/redirect
        - myandroidapp://oauth2/redirect
        - myiosapp://oauth2/redirect
  front-url: https://${SERVER_IP}

server:
  port: 8443
  ssl:
    key-store: file:certs/keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: keystore
    trust-store: file:certs/truststore.p12
    trust-store-password: password
    trustStoreType: PKCS12
  error:
    include-message: never
